#!/usr/bin/env python3
"""Generate the Jira operations an anonymous caller may read.

Jira's platform specification says, operation by operation, which operations
"can be accessed anonymously". A caller presenting no credentials is Jira's
anonymous user on those operations, with access coming only from permissions
granted to anyone. This writes the reading operations among them into a Go
table from the pinned specification; ``--check`` verifies the committed table.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "api/specs/jira-v3.json"
DESTINATION = ROOT / "internal/api3/anonymous_operations_generated.go"

# POST operations that only read: searches, parsing, evaluation and bulk reads.
READING_POSTS = {
    "/rest/api/3/comment/list",
    "/rest/api/3/issue/bulkfetch",
    "/rest/api/3/expression/eval",
    "/rest/api/3/expression/evaluate",
    "/rest/api/3/jql/parse",
    "/rest/api/3/permissions/check",
    "/rest/api/3/permissions/project",
    "/rest/api/3/search",
    "/rest/api/3/search/jql",
    "/rest/api/3/search/approximate-count",
    "/rest/api/3/issue/{issueIdOrKey}/changelog/list",
}


def operations():
    document = json.loads(SPEC.read_text())
    rows = []
    for path, item in document["paths"].items():
        for method, operation in item.items():
            if not isinstance(operation, dict) or "responses" not in operation:
                continue
            if "accessed anonymously" not in (operation.get("description") or ""):
                continue
            if method == "get" or (method == "post" and path in READING_POSTS):
                parameters = len(re.findall(r"\{[^}]+\}", path))
                literal = len(re.sub(r"\{[^}]+\}", "", path))
                pattern = "^" + re.sub(r"\\\{[^}]+\\\}", "[^/]+", re.escape(path)) + "/?$"
                rows.append((parameters, -literal, method.upper(), path, pattern))
    rows.sort()
    return rows


def render():
    lines = [
        "// Code generated by api/conformance/anonymous_operations.py; DO NOT EDIT.",
        "",
        "package api3",
        "",
        "// anonymousOperationTable lists the Jira operations an anonymous caller may",
        "// read, most specific path first.",
        "var anonymousOperationTable = []anonymousOperationRow{",
    ]
    for _, _, method, path, pattern in operations():
        lines.append(f"\t{{Method: {json.dumps(method)}, Path: {json.dumps(path)}, Pattern: {json.dumps(pattern)}}},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text() != content:
            print(f"{DESTINATION} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"Anonymous operations current ({content.count('Method:')} operations)")
        return 0
    DESTINATION.write_text(content)
    print(f"Wrote {content.count('Method:')} anonymous operations to {DESTINATION.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
