#!/usr/bin/env python3
"""Generate the Connect scope each pinned Confluence operation requires.

Atlassian marks every Confluence REST operation with the Connect scope an app
must hold to call it (``x-atlassian-connect-scope``). The app gateway enforces
those scopes, so this writes them into a Go table from the pinned
specifications. ``--check`` verifies the committed table is current.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPECS = [
    (ROOT / "api/specs/confluence-v2.json", "/wiki/api/v2"),
    (ROOT / "api/specs/confluence-v1.json", ""),
]
DESTINATION = ROOT / "internal/apps/confluence_scopes_generated.go"
METHODS = ("get", "post", "put", "patch", "delete", "head", "options")


def operations():
    rows = []
    for spec, prefix in SPECS:
        document = json.loads(spec.read_text())
        for path, item in document["paths"].items():
            for method in METHODS:
                operation = item.get(method)
                if not isinstance(operation, dict):
                    continue
                full = prefix + path
                parameters = len(re.findall(r"\{[^}]+\}", full))
                literal = len(re.sub(r"\{[^}]+\}", "", full))
                pattern = "^" + re.sub(r"\\\{[^}]+\\\}", "[^/]+", re.escape(full)) + "/?$"
                rows.append((parameters, -literal, method.upper(), full, pattern, operation.get("x-atlassian-connect-scope", "READ")))
    rows.sort()
    return rows


def render():
    lines = [
        "// Code generated by api/conformance/confluence_app_scopes.py; DO NOT EDIT.",
        "",
        "package apps",
        "",
        "// confluenceScopeTable lists every pinned Confluence operation with the",
        "// Connect scope it requires, most specific path first.",
        "var confluenceScopeTable = []confluenceScopeRow{",
    ]
    for _, _, method, path, pattern, scope in operations():
        lines.append(f"\t{{Method: {json.dumps(method)}, Path: {json.dumps(path)}, Pattern: {json.dumps(pattern)}, Scope: {json.dumps(scope)}}},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text() != content:
            print(f"{DESTINATION} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"Confluence operation scopes current ({content.count('Method:')} operations)")
        return 0
    DESTINATION.write_text(content)
    print(f"Wrote {content.count('Method:')} operation scopes to {DESTINATION.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
