CREATE SEQUENCE jira_dashboard_id START 10000;
CREATE TABLE dashboards (
 id text PRIMARY KEY DEFAULT nextval('jira_dashboard_id')::text,
 workspace_id text NOT NULL REFERENCES workspaces(id),
 owner_id text NOT NULL REFERENCES users(id),
 name text NOT NULL CHECK (length(name) BETWEEN 1 AND 255),
 description text NOT NULL DEFAULT '',
 share_permissions jsonb NOT NULL DEFAULT '[]',
 edit_permissions jsonb NOT NULL DEFAULT '[]',
 layout text NOT NULL DEFAULT 'AA' CHECK (layout IN ('A','AA','AB','BA','AAA')),
 refresh_ms integer NOT NULL DEFAULT 0 CHECK (refresh_ms IN (0,60000,300000,900000)),
 deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX dashboards_workspace ON dashboards(workspace_id) WHERE NOT deleted;
CREATE TABLE dashboard_favourites (
 dashboard_id text NOT NULL REFERENCES dashboards(id) ON DELETE CASCADE,
 user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 PRIMARY KEY(dashboard_id,user_id)
);
CREATE TABLE dashboard_gadgets (
 id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
 dashboard_id text NOT NULL REFERENCES dashboards(id) ON DELETE CASCADE,
 module_key text NOT NULL,
 title text NOT NULL,
 color text NOT NULL DEFAULT 'blue',
 col integer NOT NULL DEFAULT 0 CHECK (col BETWEEN 0 AND 2),
 row integer NOT NULL DEFAULT 0 CHECK (row >= 0)
);
CREATE INDEX dashboard_gadgets_order ON dashboard_gadgets(dashboard_id,col,row,id);
CREATE TABLE dashboard_gadget_properties (
 gadget_id bigint NOT NULL REFERENCES dashboard_gadgets(id) ON DELETE CASCADE,
 key text NOT NULL CHECK (length(key) BETWEEN 1 AND 255),
 value jsonb NOT NULL,
 PRIMARY KEY(gadget_id,key)
);
