ALTER TABLE workflows
  ADD COLUMN IF NOT EXISTS draft_def JSONB,
  ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS draft_updated_at TIMESTAMPTZ;
