CREATE TABLE wiki_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000000) PRIMARY KEY,
  space_id BIGINT NOT NULL REFERENCES wiki_spaces(id) ON DELETE CASCADE,
  parent_page_id BIGINT REFERENCES wiki_pages(id) ON DELETE RESTRICT,
  parent_content_id BIGINT REFERENCES wiki_content(id) ON DELETE RESTRICT,
  root_page_id BIGINT REFERENCES wiki_pages(id) ON DELETE RESTRICT,
  type TEXT NOT NULL CHECK(type IN ('folder','database','embed','whiteboard')),
  title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 255),
  status TEXT NOT NULL DEFAULT 'current' CHECK(status IN ('current','archived','trashed')),
  embed_url TEXT NOT NULL DEFAULT '',
  author_id TEXT NOT NULL REFERENCES users(id),
  owner_id TEXT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
  CHECK(num_nonnulls(parent_page_id,parent_content_id) <= 1)
);

CREATE TABLE wiki_content_versions (
  content_id BIGINT NOT NULL REFERENCES wiki_content(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  embed_url TEXT NOT NULL DEFAULT '',
  author_id TEXT NOT NULL REFERENCES users(id),
  message TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY(content_id,version)
);

CREATE TABLE wiki_content_properties (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  content_id BIGINT NOT NULL REFERENCES wiki_content(id) ON DELETE CASCADE,
  key TEXT NOT NULL CHECK(length(key) BETWEEN 1 AND 255),
  value JSONB NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
  author_id TEXT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(content_id,key)
);

CREATE TABLE wiki_content_property_versions (
  property_id BIGINT NOT NULL REFERENCES wiki_content_properties(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  value JSONB NOT NULL,
  author_id TEXT NOT NULL REFERENCES users(id),
  message TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY(property_id,version)
);

CREATE INDEX wiki_content_space_type ON wiki_content(space_id,type,status,id);
CREATE INDEX wiki_content_parent_page ON wiki_content(parent_page_id,status,id);
CREATE INDEX wiki_content_parent_content ON wiki_content(parent_content_id,status,id);
CREATE INDEX wiki_content_root_page ON wiki_content(root_page_id,status,id);
CREATE INDEX wiki_content_properties_content ON wiki_content_properties(content_id,key,id);
