-- Avatars an administrator loads for an issue type. The image belongs to the
-- site that loaded it, and selecting it is the site's own change to the type.
CREATE TABLE issue_type_avatars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10500) PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  issue_type_id TEXT NOT NULL REFERENCES issue_types(id) ON DELETE CASCADE,
  media_type TEXT NOT NULL CHECK (media_type IN ('image/png','image/jpeg','image/gif')),
  data BYTEA NOT NULL CHECK (octet_length(data) BETWEEN 1 AND 1048576),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
