-- People and identity as Jira exposes them.
--
-- User properties are app data stored against a person in one site, separate
-- from the Confluence user properties a site keeps. Preferences are a person's
-- own settings, including their locale; columns are the issue table columns a
-- person chose. All of them belong to the site, since one person can use many.

CREATE TABLE jira_user_properties (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key TEXT NOT NULL CHECK (length(key) BETWEEN 1 AND 255),
  value JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id, key)
);

CREATE TABLE jira_user_preferences (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key TEXT NOT NULL CHECK (length(key) BETWEEN 1 AND 255),
  value TEXT NOT NULL CHECK (length(value) <= 255),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id, key)
);

CREATE TABLE jira_user_columns (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  columns TEXT[] NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id)
);

-- One store for the custom avatars of projects, issue types and priorities.
-- System avatars are a fixed catalogue in code with ids below 20000, so custom
-- ids start above them.
CREATE TABLE universal_avatars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 20000) PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  owner_type TEXT NOT NULL CHECK (owner_type IN ('project','issuetype','priority')),
  owner_id TEXT NOT NULL,
  media_type TEXT NOT NULL CHECK (media_type IN ('image/png','image/jpeg','image/gif')),
  data BYTEA NOT NULL CHECK (octet_length(data) BETWEEN 1 AND 1048576),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX universal_avatars_owner ON universal_avatars (workspace_id, owner_type, owner_id, id);

-- Issue type avatars move into the shared store with the ids clients already hold.
INSERT INTO universal_avatars (id, workspace_id, owner_type, owner_id, media_type, data, created_at)
SELECT id, workspace_id, 'issuetype', issue_type_id, media_type, data, created_at FROM issue_type_avatars;
SELECT setval(pg_get_serial_sequence('universal_avatars','id'),
  GREATEST((SELECT COALESCE(max(id), 19999) FROM universal_avatars), 19999));
DROP TABLE issue_type_avatars;

-- The avatar a project shows. Null means the default system avatar.
ALTER TABLE projects ADD COLUMN avatar_id BIGINT;
