-- Jira's issue-level surface: comment ids, edits, visibility and properties;
-- per-site issue link types with Jira's ids; numeric issue link ids; remote
-- issue links; issue archiving; issue view history for the issue picker;
-- redaction records; issue panel pins; archived issue exports.

-- Comments carry the numeric ids clients see, who last edited them and when,
-- and an optional group or project role restriction.
CREATE SEQUENCE jira_comment_id START 10000;
ALTER TABLE comments
  ADD COLUMN jira_id BIGINT,
  ADD COLUMN updated_at TIMESTAMPTZ,
  ADD COLUMN update_author_id TEXT,
  ADD COLUMN visibility_type TEXT CHECK (visibility_type IN ('group','role')),
  ADD COLUMN visibility_value TEXT,
  ADD CONSTRAINT comments_visibility_complete CHECK ((visibility_type IS NULL) = (visibility_value IS NULL));
UPDATE comments c SET jira_id = 9999 + o.n
FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) n FROM comments) o WHERE o.id=c.id;
SELECT setval('jira_comment_id', GREATEST(10000, COALESCE((SELECT max(jira_id) + 1 FROM comments), 10000)), false);
UPDATE comments SET updated_at=created_at;
ALTER TABLE comments
  ALTER COLUMN jira_id SET DEFAULT nextval('jira_comment_id'),
  ALTER COLUMN jira_id SET NOT NULL,
  ALTER COLUMN updated_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET NOT NULL;
ALTER SEQUENCE jira_comment_id OWNED BY comments.jira_id;
CREATE UNIQUE INDEX comments_jira_id ON comments(jira_id);

CREATE TABLE jira_comment_properties (
  comment_id TEXT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  key TEXT NOT NULL CHECK (char_length(key) BETWEEN 1 AND 255),
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (comment_id, key)
);

-- Issue link types belong to a site. Every site starts with Jira's four.
CREATE SEQUENCE jira_issue_link_type_id START 10004;
ALTER TABLE issue_link_types
  ADD COLUMN workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE,
  ADD COLUMN jira_id BIGINT;

CREATE OR REPLACE FUNCTION provision_workspace_issue_link_types(target TEXT)
RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO issue_link_types(id,workspace_id,jira_id,name,inward,outward)
  SELECT 'lt_' || substr(md5(target || ':' || d.jira_id), 1, 16), target, d.jira_id, d.name, d.inward, d.outward
  FROM (VALUES
    (10000::BIGINT, 'Blocks', 'is blocked by', 'blocks'),
    (10001::BIGINT, 'Cloners', 'is cloned by', 'clones'),
    (10002::BIGINT, 'Duplicate', 'is duplicated by', 'duplicates'),
    (10003::BIGINT, 'Relates', 'relates to', 'relates to')
  ) AS d(jira_id, name, inward, outward)
  WHERE NOT EXISTS (SELECT 1 FROM issue_link_types t WHERE t.workspace_id=target AND t.jira_id=d.jira_id);
END;
$$;

SELECT provision_workspace_issue_link_types(id) FROM workspaces;
UPDATE issue_links l SET link_type_id = site.id
FROM issue_link_types shared, issue_link_types site
WHERE shared.id = l.link_type_id AND shared.workspace_id IS NULL
  AND site.workspace_id = l.workspace_id
  AND site.jira_id = CASE shared.id WHEN 'lt_blocks' THEN 10000 WHEN 'lt_duplicates' THEN 10002 ELSE 10003 END;
DELETE FROM issue_link_types WHERE workspace_id IS NULL;
ALTER TABLE issue_link_types
  ALTER COLUMN workspace_id SET NOT NULL,
  ALTER COLUMN jira_id SET DEFAULT nextval('jira_issue_link_type_id'),
  ALTER COLUMN jira_id SET NOT NULL;
CREATE UNIQUE INDEX issue_link_types_site_jira_id ON issue_link_types(workspace_id, jira_id);
CREATE UNIQUE INDEX issue_link_types_site_name ON issue_link_types(workspace_id, lower(name));

CREATE OR REPLACE FUNCTION provision_workspace_issue_link_types_after_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  PERFORM provision_workspace_issue_link_types(NEW.id);
  RETURN NEW;
END;
$$;
CREATE TRIGGER provision_workspace_issue_link_types_after_insert
AFTER INSERT ON workspaces FOR EACH ROW
EXECUTE FUNCTION provision_workspace_issue_link_types_after_insert();

-- Issue links carry numeric ids.
CREATE SEQUENCE jira_issue_link_id START 10000;
ALTER TABLE issue_links ADD COLUMN jira_id BIGINT;
UPDATE issue_links l SET jira_id = 9999 + o.n
FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) n FROM issue_links) o WHERE o.id=l.id;
SELECT setval('jira_issue_link_id', GREATEST(10000, COALESCE((SELECT max(jira_id) + 1 FROM issue_links), 10000)), false);
ALTER TABLE issue_links
  ALTER COLUMN jira_id SET DEFAULT nextval('jira_issue_link_id'),
  ALTER COLUMN jira_id SET NOT NULL;
ALTER SEQUENCE jira_issue_link_id OWNED BY issue_links.jira_id;
CREATE UNIQUE INDEX issue_links_jira_id ON issue_links(jira_id);

-- Remote issue links: items in other systems an issue points at.
CREATE TABLE remote_issue_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  global_id TEXT CHECK (global_id IS NULL OR char_length(global_id) BETWEEN 1 AND 255),
  application JSONB,
  relationship TEXT,
  object JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX remote_issue_links_global_id ON remote_issue_links(issue_id, global_id) WHERE global_id IS NOT NULL;
CREATE INDEX remote_issue_links_issue ON remote_issue_links(issue_id, id);

-- Archived issues stay readable but leave search, boards and pickers.
ALTER TABLE issues
  ADD COLUMN archived_at TIMESTAMPTZ,
  ADD COLUMN archived_by TEXT;
CREATE INDEX issues_archived ON issues(workspace_id, archived_at) WHERE archived_at IS NOT NULL;

CREATE TABLE archived_issue_exports (
  task_id TEXT PRIMARY KEY REFERENCES api_tasks(id) ON DELETE CASCADE,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  requested_by TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The issues a person viewed, newest first, for the issue picker's history.
CREATE TABLE issue_views (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  viewed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id, issue_id)
);
CREATE INDEX issue_views_recent ON issue_views(workspace_id, user_id, viewed_at DESC);

-- Each redaction is recorded once by its external id.
CREATE TABLE issue_redactions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  external_id TEXT NOT NULL,
  issue_id TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('issuefieldvalue','issue-comment','issue-worklog')),
  entity_id TEXT NOT NULL,
  reason TEXT NOT NULL,
  redacted_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, external_id)
);

-- Issue panels an administrator pinned to projects.
CREATE TABLE issue_panel_project_pins (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  module_id TEXT NOT NULL REFERENCES app_modules(id) ON DELETE CASCADE,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  pinned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, module_id, project_id)
);

-- Attachments and worklogs carry the numeric ids clients see.
CREATE SEQUENCE jira_attachment_id START 10000;
ALTER TABLE attachments ADD COLUMN jira_id BIGINT;
UPDATE attachments a SET jira_id = 9999 + o.n
FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) n FROM attachments) o WHERE o.id=a.id;
SELECT setval('jira_attachment_id', GREATEST(10000, COALESCE((SELECT max(jira_id) + 1 FROM attachments), 10000)), false);
ALTER TABLE attachments
  ALTER COLUMN jira_id SET DEFAULT nextval('jira_attachment_id'),
  ALTER COLUMN jira_id SET NOT NULL;
ALTER SEQUENCE jira_attachment_id OWNED BY attachments.jira_id;
CREATE UNIQUE INDEX attachments_jira_id ON attachments(jira_id);

CREATE SEQUENCE jira_worklog_id START 10000;
ALTER TABLE worklogs ADD COLUMN jira_id BIGINT;
UPDATE worklogs w SET jira_id = 9999 + o.n
FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) n FROM worklogs) o WHERE o.id=w.id;
SELECT setval('jira_worklog_id', GREATEST(10000, COALESCE((SELECT max(jira_id) + 1 FROM worklogs), 10000)), false);
ALTER TABLE worklogs
  ALTER COLUMN jira_id SET DEFAULT nextval('jira_worklog_id'),
  ALTER COLUMN jira_id SET NOT NULL;
ALTER SEQUENCE jira_worklog_id OWNED BY worklogs.jira_id;
CREATE UNIQUE INDEX worklogs_jira_id ON worklogs(jira_id);
ALTER TABLE deleted_worklogs ADD COLUMN jira_id BIGINT;
