import { expect, test, Page } from '@playwright/test';
import axe from 'axe-core';
import * as fs from 'fs';
import * as path from 'path';

function apiAuthHeader(): string {
  const tokens = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', 'seed-tokens.json'), 'utf8'));
  const token = process.env.ZZIRA_API_TOKEN ?? tokens['demo@zzira.dev'];
  return 'Basic ' + Buffer.from(`demo@zzira.dev:${token}`).toString('base64');
}

async function accessible(page: import('@playwright/test').Page) {
  // Axe counts controls under the sticky header as covered, so pages are
  // checked from the top rather than wherever an anchor scrolled them.
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.addScriptTag({ content: axe.source });
  const violations = await page.evaluate(async () => (await (window as any).axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa'] } })).violations);
  expect(violations).toEqual([]);
}

async function downloadCSV(page: Page): Promise<{ name: string; lines: string[] }> {
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('link', { name: 'Download CSV' }).click()]);
  return { name: download.suggestedFilename(), lines: fs.readFileSync((await download.path())!, 'utf8').trim().split('\n') };
}

test('admin creates a service project with Jira Service Management request types', async ({ page }) => {
  test.setTimeout(180_000);
  await page.goto('/login');
  await page.fill('#login-email', 'demo@zzira.dev');
  await page.fill('#login-password', 'demo1234');
  await page.click('button[type=submit]');
  const key = `S${String(Date.now()).slice(-7)}`;
  await page.goto('/projects/new');
  await page.getByLabel('Name').fill(`Service desk ${key}`);
  await page.getByLabel('Key').fill(key);
  await page.getByLabel('Template').selectOption('com.atlassian.servicedesk:simplified-it-service-management');
  await page.getByLabel('Description').fill('Customer requests and production incidents');
  await page.getByRole('button', { name: 'Create project' }).click();
  await expect(page).toHaveURL(`/projects/${key}`);
  await expect(page.getByRole('heading', { name: `Service desk ${key}`, level: 1 })).toBeVisible();

  const auth = { Authorization: apiAuthHeader() };
  const projectResponse = await page.request.get(`/rest/api/3/project/${key}`, { headers: auth });
  expect(projectResponse.status()).toBe(200);
  expect(await projectResponse.json()).toMatchObject({ key, projectTypeKey: 'service_desk' });
  let desk: any;
  let deskStart = 0;
  while (!desk) {
    const desksResponse = await page.request.get(`/rest/servicedeskapi/servicedesk?start=${deskStart}&limit=100`, { headers: auth });
    expect(desksResponse.status()).toBe(200);
    const desks = await desksResponse.json();
    desk = desks.values.find((candidate: any) => candidate.projectKey === key);
    if (desk || desks.isLastPage) break;
    deskStart += desks.size;
  }
  expect(desk).toBeTruthy();
  const requestTypesResponse = await page.request.get(`/rest/servicedeskapi/servicedesk/${desk.id}/requesttype`, { headers: auth });
  expect(requestTypesResponse.status()).toBe(200);
  const requestTypes = await requestTypesResponse.json();
  expect(requestTypes.values.map((requestType: any) => requestType.name)).toEqual(expect.arrayContaining(['Get IT help', 'Report an incident', 'Investigate a problem', 'Request a change']));
  const incidentRequestType = requestTypes.values.find((requestType: any) => requestType.name === 'Report an incident');
  const changeRequestType = requestTypes.values.find((requestType: any) => requestType.name === 'Request a change');
  expect(incidentRequestType).toBeTruthy();
  expect(changeRequestType).toBeTruthy();
  const fieldsResponse = await page.request.get(`/rest/servicedeskapi/servicedesk/${desk.id}/requesttype/${requestTypes.values[0].id}/field`, { headers: auth });
  expect(fieldsResponse.status()).toBe(200);
  expect((await fieldsResponse.json()).requestTypeFields).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: 'summary', required: true })]));

  const knowledgeKey = `KB${String(Date.now()).slice(-8)}`;
  const spaceResponse = await page.request.post('/wiki/api/v2/spaces', {
    headers: auth,
    data: { key: knowledgeKey, name: `Support knowledge ${key}`, description: { representation: 'plain', value: 'Self-service support articles' }, createPrivateSpace: false },
  });
  expect(spaceResponse.status()).toBe(201);
  const knowledgeSpace = await spaceResponse.json();
  const articleResponse = await page.request.post('/wiki/api/v2/pages', {
    headers: auth,
    data: { spaceId: knowledgeSpace.id, title: `Resolve checkout errors ${key}`, status: 'current', body: { representation: 'storage', value: '<p>Restart the checkout worker and verify the payment queue.</p>' } },
  });
  expect(articleResponse.status()).toBe(200);

  await page.goto(`/service/agent/${desk.id}`);
  const operationsSettings = page.locator('#operations-settings');
  await expect(operationsSettings.getByRole('heading', { name: 'Risk, CAB, on-call, and reviews' })).toBeVisible();
  await operationsSettings.getByLabel('CAB approval threshold').fill('9');
  await operationsSettings.getByLabel('Incident review due in days').fill('3');
  await operationsSettings.getByRole('checkbox', { name: 'Demo User' }).check();
  await operationsSettings.getByRole('button', { name: 'Save operations policy' }).click();
  const now = new Date();
  const localDateTime = (value: Date) => value.toISOString().slice(0, 16);
  await page.locator('#operations-settings').getByLabel('Rotation label').fill('Primary operations');
  await page.locator('#operations-settings').getByLabel('On-call owner').selectOption({ label: 'Demo User' });
  await page.locator('#operations-settings').getByLabel('Starts').fill(localDateTime(new Date(now.getTime() - 3_600_000)));
  await page.locator('#operations-settings').getByLabel('Ends').fill(localDateTime(new Date(now.getTime() + 86_400_000)));
  await page.locator('#operations-settings').getByRole('button', { name: 'Add on-call shift' }).click();
  await expect(page.locator('#operations-settings')).toContainText('Primary operations');
  const escalationPolicy = page.locator('#escalation-policy');
  await escalationPolicy.getByLabel('Escalate after minutes').fill('15');
  await escalationPolicy.getByLabel('Escalation target').selectOption({ label: 'Demo User' });
  await escalationPolicy.getByRole('button', { name: 'Add escalation step' }).click();
  await expect(page.locator('#escalation-policy')).toContainText('After 15 minutes');

  await page.goto('/service');
  await expect(page.getByRole('heading', { name: 'How can we help?', level: 1 })).toBeVisible();
  await accessible(page);
  // A site administrator brands the help center and announces news on its home page.
  const helpCenterSettings = page.locator('#help-center-settings');
  await helpCenterSettings.locator('summary').click();
  await helpCenterSettings.getByLabel('Help center name').fill('Acme help');
  await helpCenterSettings.getByLabel('Banner, link and button colour').fill('#0052CC');
  await helpCenterSettings.getByLabel('Announcement title').fill('Planned maintenance');
  await helpCenterSettings.getByLabel('Announcement message').fill('Email is offline on Saturday.');
  await helpCenterSettings.getByRole('button', { name: 'Save help center' }).click();
  const announcement = page.getByRole('region', { name: 'Planned maintenance' });
  await expect(announcement).toContainText('Email is offline on Saturday.');
  await expect(page.locator('.service-hero .eyebrow')).toHaveText('Acme help');
  await expect(page.locator('.service-hero')).toHaveCSS('background-color', 'rgb(0, 82, 204)');
  await accessible(page);
  // Clearing the settings returns the help center to its defaults.
  await page.locator('#help-center-settings summary').click();
  for (const label of ['Help center name', 'Banner, link and button colour', 'Announcement title', 'Announcement message']) {
    await page.locator('#help-center-settings').getByLabel(label).fill('');
  }
  await page.locator('#help-center-settings').getByRole('button', { name: 'Save help center' }).click();
  await expect(page.getByRole('region', { name: 'Planned maintenance' })).toHaveCount(0);
  await expect(page.locator('.service-hero .eyebrow')).toHaveText('Help center');
  await page.getByRole('link', { name: `Service desk ${key}` }).click();
  await expect(page.getByRole('heading', { name: `Service desk ${key}`, level: 1 })).toBeVisible();
  await page.getByRole('link', { name: /Report an incident/ }).click();
  await expect(page.getByRole('heading', { name: 'Report an incident', level: 1 })).toBeVisible();
  const requestSummary = `Checkout incident ${Date.now()}`;
  await page.getByLabel('Summary').fill(requestSummary);
  await page.getByLabel('Description').fill('Customers receive an error when completing checkout.');
  await page.getByRole('button', { name: 'Send request' }).click();
  await expect(page).toHaveURL(new RegExp(`/service/requests/${key}-\\d+$`));
  const requestURL = page.url();
  await expect(page.getByRole('heading', { name: requestSummary, level: 1 })).toBeVisible();
  await expect(page.locator('.service-current-status')).toHaveText('To Do');
  await expect(page.getByRole('heading', { name: 'Service goals' })).toBeVisible();
  await expect(page.locator('.service-sla-panel')).toContainText('Time to first response');
  const incidentOperations = page.locator('#operations-control');
  await expect(incidentOperations).toContainText('On call: Demo User');
  await expect(incidentOperations).toContainText('Low risk');
  await incidentOperations.getByLabel('Impact').selectOption('4');
  await incidentOperations.getByLabel('Likelihood').selectOption('3');
  await incidentOperations.getByRole('checkbox', { name: 'Coordinate as a major incident' }).check();
  await incidentOperations.getByLabel('Review status').selectOption('in_progress');
  await incidentOperations.getByLabel('Review findings').fill('Review customer impact, detection, and recovery evidence.');
  await incidentOperations.getByRole('button', { name: 'Save operations assessment' }).click();
  await expect(page.locator('#operations-control')).toContainText('High risk');
  await expect(page.locator('.service-escalation-progress')).toContainText('Demo User');
  await expect(page.locator('.service-escalation-progress')).toContainText('Waiting');
  const incidentUpdates = page.locator('#incident-updates');
  await expect(incidentUpdates.getByRole('heading', { name: 'Status updates' })).toBeVisible();
  await incidentUpdates.getByLabel('Update').fill('Checkout is unavailable. The response team is investigating.');
  await incidentUpdates.getByRole('button', { name: 'Publish status update' }).click();
  await expect(page.locator('#incident-updates')).toContainText('Checkout is unavailable. The response team is investigating.');
  // The response team takes incident roles and stakeholders follow stakeholder updates.
  await page.locator('#incident-team').getByLabel('Incident commander').selectOption({ label: 'Demo User' });
  await page.locator('#incident-team').getByRole('button', { name: 'Save Incident commander' }).click();
  await expect(page.locator('#incident-team').getByLabel('Incident commander')).not.toHaveValue('');
  await page.locator('#incident-team').getByLabel('Or email address').fill('exec.sponsor@example.test');
  await page.locator('#incident-team').getByRole('button', { name: 'Add stakeholder' }).click();
  await expect(page.locator('#incident-team')).toContainText('exec.sponsor@example.test');
  await page.locator('#incident-updates').getByLabel('Audience').selectOption('stakeholders');
  await page.locator('#incident-updates').getByLabel('Update').fill('Checkout recovers for most customers.');
  await page.locator('#incident-updates').getByRole('button', { name: 'Publish status update' }).click();
  await expect(page.locator('#incident-updates')).toContainText('Checkout recovers for most customers.');
  await expect(page.locator('#incident-updates').locator('.lozenge').filter({ hasText: 'stakeholders' })).toHaveCount(1);
  await expect(page.getByText('Customers receive an error when completing checkout.')).toBeVisible();
  await page.goto(`/service/portals/${desk.id}`);
  await expect(page.getByRole('link', { name: /Investigate a problem/ })).toBeVisible();
  await page.getByRole('link', { name: /Request a change/ }).click();
  const changeSummary = `Scale checkout workers ${Date.now()}`;
  await page.getByLabel('Summary').fill(changeSummary);
  await page.getByLabel('Description').fill('Increase capacity after approval and roll back if checkout latency rises.');
  await page.getByRole('button', { name: 'Send request' }).click();
  await expect(page.getByRole('heading', { name: changeSummary, level: 1 })).toBeVisible();
  const changeKey = page.url().split('/').pop()!;
  await expect(page.locator('.service-request-side')).toContainText('Request a change');
  const changeOperations = page.locator('#operations-control');
  await changeOperations.getByLabel('Impact').selectOption('3');
  await changeOperations.getByLabel('Likelihood').selectOption('3');
  await changeOperations.getByLabel('Change type').selectOption('normal');
  await changeOperations.getByLabel('Planned start').fill(localDateTime(new Date(now.getTime() + 172_800_000)));
  await changeOperations.getByLabel('Planned end').fill(localDateTime(new Date(now.getTime() + 176_400_000)));
  await changeOperations.getByLabel('Rollback plan').fill('Restore the previous worker count and confirm queue latency.');
  await changeOperations.getByRole('button', { name: 'Save operations assessment' }).click();
  await expect(page.locator('#approvals')).toContainText('Change advisory board');
  await page.locator('#operations-control').getByRole('button', { name: 'Save operations assessment' }).click();
  await expect(page.locator('#approvals .service-approvals > li')).toHaveCount(1);
  await page.locator('#approvals').getByRole('button', { name: 'Approve' }).click();
  await expect(page.locator('#approvals')).toContainText('approved');
  await page.goto(`/service/portals/${desk.id}`);
  await page.locator('.service-type-card').filter({ hasText: 'Request a change' }).click();
  const overlapSummary = `Rotate checkout credentials ${Date.now()}`;
  await page.getByLabel('Summary').fill(overlapSummary);
  await page.getByLabel('Description').fill('Rotate credentials during the planned capacity change.');
  await page.getByRole('button', { name: 'Send request' }).click();
  const overlapKey = page.url().split('/').pop()!;
  const overlapOperations = page.locator('#operations-control');
  await overlapOperations.getByLabel('Impact').selectOption('2');
  await overlapOperations.getByLabel('Likelihood').selectOption('2');
  await overlapOperations.getByLabel('Planned start').fill(localDateTime(new Date(now.getTime() + 174_600_000)));
  await overlapOperations.getByLabel('Planned end').fill(localDateTime(new Date(now.getTime() + 178_200_000)));
  await overlapOperations.getByLabel('Rollback plan').fill('Restore the previous credentials.');
  await overlapOperations.getByRole('button', { name: 'Save operations assessment' }).click();
  await expect(page.locator('#change-conflicts')).toContainText(changeKey);
  await page.goto(`/service/requests/${changeKey}`);
  await expect(page.locator('#change-conflicts')).toContainText(overlapKey);
  await page.goto(`/service/agent/${desk.id}`);
  const changeCalendar = page.locator('#change-calendar');
  await expect(changeCalendar).toContainText(changeSummary);
  await expect(changeCalendar).toContainText(overlapSummary);
  await expect(changeCalendar.getByText('1 overlapping')).toHaveCount(2);
  await accessible(page);
  await page.goto(requestURL);
  const operationsLinks = page.locator('#operations-links');
  await operationsLinks.getByText('Link operations work').click();
  await operationsLinks.getByLabel('Work item key').fill(changeKey);
  await operationsLinks.getByRole('button', { name: 'Link work item' }).click();
  await expect(page.locator('#operations-links')).toContainText(changeSummary);
  await expect(page.getByRole('button', { name: 'Stop notifications' })).toBeVisible();
  await page.getByRole('button', { name: 'Stop notifications' }).click();
  await expect(page.getByRole('button', { name: 'Get notifications' })).toBeVisible();
  await page.getByRole('button', { name: 'Get notifications' }).click();
  await expect(page.getByRole('button', { name: 'Stop notifications' })).toBeVisible();
  const participantEmail = `participant-${Date.now()}@example.test`;
  const participantResponse = await page.request.post('/rest/servicedeskapi/customer', { headers: auth, data: { email: participantEmail, displayName: 'Incident stakeholder' } });
  expect(participantResponse.status()).toBe(201);
  await page.getByLabel('Add by account ID or email').fill(participantEmail);
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.locator('#participants')).toContainText('Incident stakeholder');
  await page.getByRole('button', { name: 'Remove Incident stakeholder' }).click();
  await expect(page.locator('#participants')).not.toContainText('Incident stakeholder');
  await page.getByLabel('Add to the conversation').fill('The impact is increasing across regions.');
  await page.getByRole('button', { name: 'Add comment' }).click();
  await expect(page.locator('.service-comments')).toContainText('The impact is increasing across regions.');
  await page.getByLabel('Add to the conversation').fill('Attached customer diagnostics.');
  await page.getByLabel('Attachment').setInputFiles({ name: 'diagnostics.txt', mimeType: 'text/plain', buffer: Buffer.from('checkout diagnostics') });
  await page.getByRole('button', { name: 'Add comment' }).click();
  await expect(page.locator('.service-comments')).toContainText('diagnostics.txt');
  await expect(page.getByRole('heading', { name: 'Attachments' })).toBeVisible();
  await page.getByLabel('Request approval').fill('Incident manager approval');
  await page.getByLabel('Approver').selectOption({ label: 'Demo User' });
  await page.getByRole('button', { name: 'Request approval' }).click();
  await expect(page.locator('#approvals')).toContainText('Incident manager approval');
  await page.locator('#approvals').getByRole('button', { name: 'Approve' }).click();
  await expect(page.locator('#approvals')).toContainText('approved');
  await page.getByRole('button', { name: /In Progress/ }).click();
  await expect(page.locator('.service-current-status')).toHaveText('In Progress');
  await accessible(page);
  await page.locator('[data-theme-toggle]').click();
  await accessible(page);
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto('/service');
  await expect(page.locator('.service-request-list')).toContainText(requestSummary);
  await page.setViewportSize({ width: 1280, height: 720 });
  const impactFieldName = `Affected orders ${Date.now()}`;
  const impactFieldResponse = await page.request.post('/rest/api/3/field', {
    headers: auth,
    data: { name: impactFieldName, type: 'number', description: 'Estimated affected orders per minute.' },
  });
  expect(impactFieldResponse.status()).toBe(201);
  const impactField = await impactFieldResponse.json();
  await page.goto(`/service/agent/${desk.id}`);
  await expect(page.getByRole('heading', { name: 'Queues', level: 1 })).toBeVisible();
  await expect(page.getByRole('link', { name: 'SLA attention', exact: true })).toBeVisible();
  await expect(page.locator('.service-agent-table')).toContainText(requestSummary);
  const customQueueName = `Checkout incidents ${String(Date.now()).slice(-6)}`;
  const queueSettings = page.locator('#queue-settings');
  await expect(queueSettings.getByRole('heading', { name: 'Custom queues' })).toBeVisible();
  await queueSettings.locator('.service-queue-create').getByLabel('Queue name').fill(customQueueName);
  await queueSettings.locator('.service-queue-create').getByLabel('JQL').fill(`summary ~ "${requestSummary}" ORDER BY created ASC`);
  await queueSettings.getByRole('button', { name: 'Create queue' }).click();
  await expect(page.getByRole('heading', { name: customQueueName, level: 2 })).toBeVisible();
  await expect(page.locator('.service-agent-table')).toContainText(requestSummary);
  const updatedQueueName = `${customQueueName} urgent`;
  const customQueueCard = page.locator('#queue-settings article').filter({ has: page.locator(`input[value="${customQueueName}"]`) });
  await customQueueCard.getByLabel('Queue name').fill(updatedQueueName);
  await customQueueCard.getByRole('button', { name: 'Save queue' }).click();
  await expect(page.getByRole('heading', { name: updatedQueueName, level: 2 })).toBeVisible();
  await page.locator('#queue-settings').getByRole('button', { name: `Delete queue ${updatedQueueName}` }).click();
  await expect(page.locator('.service-queue-nav')).not.toContainText(updatedQueueName);
  const requestFormSettings = page.locator('#request-forms');
  await expect(requestFormSettings.getByRole('heading', { name: 'Request type forms' })).toBeVisible();
  const incidentForm = requestFormSettings.locator('form').filter({ has: page.getByRole('heading', { name: 'Report an incident', level: 3 }) });
  const impactFieldSettings = incidentForm.locator('fieldset').filter({ hasText: impactFieldName });
  await impactFieldSettings.getByRole('checkbox', { name: 'Show on portal' }).check();
  await impactFieldSettings.getByRole('checkbox', { name: 'Required' }).check();
  await impactFieldSettings.getByLabel('Help text').fill('Estimate the affected orders per minute.');
  await incidentForm.getByRole('button', { name: 'Save Report an incident form' }).click();
  await expect(page).toHaveURL(new RegExp(`/service/agent/${desk.id}.*#request-forms$`));
  await page.goto(`/service/portals/${desk.id}/request/${incidentRequestType.id}`);
  await expect(page.getByLabel(impactFieldName)).toBeVisible();
  await expect(page.getByText('Estimate the affected orders per minute.')).toBeVisible();
  const dynamicRequestSummary = `Impact-qualified incident ${Date.now()}`;
  await page.getByLabel('Summary').fill(dynamicRequestSummary);
  await page.getByLabel('Description').fill('The portal form captures structured impact for routing.');
  await page.getByLabel(impactFieldName).fill('42.5');
  await page.getByRole('button', { name: 'Send request' }).click();
  await expect(page.getByRole('heading', { name: dynamicRequestSummary, level: 1 })).toBeVisible();
  await expect(page.locator('.service-request-fields')).toContainText(impactFieldName);
  await expect(page.locator('.service-request-fields')).toContainText('42.5');
  // Select, multi-select and user picker fields ask for options and people in their own terms.
  const serviceProject = await (await page.request.get(`/rest/api/3/project/${key}`, { headers: auth })).json();
  const choiceField = async (name: string, type: string, values: string[]) => {
    const created = await page.request.post('/rest/api/3/field', { headers: auth, data: { name, type: `com.atlassian.jira.plugin.system.customfieldtypes:${type}` } });
    expect(created.status()).toBe(201);
    const id = (await created.json()).id as string;
    const contexts = await (await page.request.get(`/rest/api/3/field/${id}/context`, { headers: auth })).json();
    const contextID = String(contexts.values[0].id);
    expect((await page.request.put(`/rest/api/3/field/${id}/context/${contextID}/project`, { headers: auth, data: { projectIds: [String(serviceProject.id)] } })).status()).toBe(204);
    if (values.length) expect((await page.request.post(`/rest/api/3/field/${id}/context/${contextID}/option`, { headers: auth, data: { options: values.map(value => ({ value })) } })).status()).toBe(200);
  };
  const choiceStamp = Date.now();
  const platformName = `Affected platform ${choiceStamp}`;
  const regionsName = `Affected regions ${choiceStamp}`;
  const contactName = `Escalation contact ${choiceStamp}`;
  await choiceField(platformName, 'select', ['Web', 'Mobile']);
  await choiceField(regionsName, 'multiselect', ['EU', 'US']);
  await choiceField(contactName, 'userpicker', []);
  // A version picker offers the service project's versions.
  const releaseName = `Affected release ${choiceStamp}`;
  const versionName = `Portal release ${choiceStamp}`;
  expect((await page.request.post('/rest/api/3/version', { headers: auth, data: { projectId: Number(serviceProject.id), name: versionName } })).status()).toBe(201);
  await choiceField(releaseName, 'version', []);
  await page.goto(`/service/agent/${desk.id}`);
  const choicesForm = page.locator('#request-forms form').filter({ has: page.getByRole('heading', { name: 'Report an incident', level: 3 }) });
  const fieldSettings = (name: string) => choicesForm.locator(`xpath=.//fieldset[legend[normalize-space()="${name}"]]`);
  for (const name of [platformName, regionsName, contactName, releaseName]) await fieldSettings(name).getByRole('checkbox', { name: 'Show on portal' }).check();
  // The contact is asked for only when the platform is Mobile.
  await fieldSettings(contactName).getByLabel('Show only when').selectOption({ label: `${platformName} has one of the options below` });
  await fieldSettings(contactName).getByRole('group', { name: `Options of ${platformName} that show ${contactName}` }).getByLabel('Mobile').check();
  await choicesForm.getByRole('button', { name: 'Save Report an incident form' }).click();
  await page.goto(`/service/portals/${desk.id}/request/${incidentRequestType.id}`);
  const portalFields = await (await page.request.get(`/rest/servicedeskapi/servicedesk/${desk.id}/requesttype/${incidentRequestType.id}/field`, { headers: auth })).json();
  const releaseField = portalFields.requestTypeFields.find((field: any) => field.name === releaseName);
  expect(releaseField.jiraSchema.custom).toBe('com.atlassian.jira.plugin.system.customfieldtypes:version');
  expect(releaseField.validValues.map((value: any) => value.label)).toContain(versionName);
  const choicesSummary = `Structured incident ${choiceStamp}`;
  await page.getByLabel('Summary').fill(choicesSummary);
  await page.getByLabel('Description').fill('Portal choices route the incident.');
  await page.getByLabel(impactFieldName).fill('7');
  await expect(page.getByLabel(contactName)).toBeHidden();
  await page.getByLabel(platformName).selectOption({ label: 'Web' });
  await expect(page.getByLabel(contactName)).toBeHidden();
  await page.getByLabel(platformName).selectOption({ label: 'Mobile' });
  await expect(page.getByLabel(contactName)).toBeVisible();
  const regions = page.getByRole('group', { name: regionsName });
  await regions.getByLabel('EU').check();
  await regions.getByLabel('US').check();
  await page.getByLabel(contactName).fill('nobody@example.test');
  await page.getByLabel(releaseName).selectOption({ label: versionName });
  await accessible(page);
  await page.getByRole('button', { name: 'Send request' }).click();
  // An email that names no member is refused with the answers kept.
  await expect(page.getByRole('alert')).toHaveText('No active member of this site uses nobody@example.test.');
  await expect(page.getByLabel(platformName)).not.toHaveValue('');
  await expect(regions.getByLabel('US')).toBeChecked();
  await expect(page.getByLabel(releaseName)).not.toHaveValue('');
  await page.getByLabel(contactName).fill('demo@zzira.dev');
  await page.getByRole('button', { name: 'Send request' }).click();
  await expect(page.getByRole('heading', { name: choicesSummary, level: 1 })).toBeVisible();
  await expect(page.locator('.service-request-fields')).toContainText('Mobile');
  await expect(page.locator('.service-request-fields')).toContainText('EU, US');
  await expect(page.locator('.service-request-fields')).toContainText('Demo User');
  await expect(page.locator('.service-request-fields')).toContainText(versionName);
  await accessible(page);
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto(`/service/agent/${desk.id}`);
  await page.getByRole('link', { name: 'Unassigned requests', exact: true }).click();
  await expect(page.locator('.service-agent-table')).toContainText(requestSummary);
  const requestRow = page.getByRole('row').filter({ hasText: requestSummary });
  await requestRow.getByRole('button', { name: 'Assign to me' }).click();
  await page.getByRole('link', { name: 'Assigned to me', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: requestSummary }).getByRole('button', { name: 'Unassign' })).toBeVisible();
  // The queue's action bar changes the selected requests together.
  const bulk = page.locator('#bulk-requests');
  const assignedRow = page.getByRole('row').filter({ hasText: requestSummary });
  await page.getByLabel('Select all requests in Assigned to me').check();
  await expect(assignedRow.getByRole('checkbox')).toBeChecked();
  await page.getByLabel('Select all requests in Assigned to me').uncheck();
  await assignedRow.getByRole('checkbox').check();
  await bulk.getByLabel('Action').selectOption('comment');
  await bulk.getByLabel('Comment', { exact: true }).fill('Checked by the queue together.');
  await bulk.getByLabel('Comment visibility').selectOption('internal');
  await accessible(page);
  await bulk.getByRole('button', { name: 'Apply to selected requests' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'requests changed' })).toHaveText(/^1 of 1 requests changed\.$/);
  // Nothing selected is refused with the reason.
  await page.locator('#bulk-requests').getByRole('button', { name: 'Apply to selected requests' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Select the requests' })).toHaveText('Select the requests to change.');
  // Moving to a status that keeps the request open leaves it in the queue;
  // a done status would take it out of this queue of open requests.
  const statuses = (await page.locator('#bulk-status option').allTextContents()).map(status => status.trim());
  const openStatus = statuses.find(status => status !== 'Done' && status !== 'Resolved' && status !== 'Closed' && status !== 'Canceled');
  expect(openStatus, `bulk statuses ${statuses.join(', ')}`).toBeTruthy();
  await page.getByRole('row').filter({ hasText: requestSummary }).getByRole('checkbox').check();
  await page.locator('#bulk-requests').getByLabel('Action').selectOption('transition');
  await page.locator('#bulk-requests').getByLabel('Status').selectOption(openStatus!);
  await page.locator('#bulk-requests').getByRole('button', { name: 'Apply to selected requests' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'requests changed' })).toHaveText(/^1 of 1 requests changed\.$/);
  await expect(page.getByRole('row').filter({ hasText: requestSummary })).toContainText(openStatus!);
  // A request already in the chosen status is named with the reason.
  await page.getByRole('row').filter({ hasText: requestSummary }).getByRole('checkbox').check();
  await page.locator('#bulk-requests').getByLabel('Action').selectOption('transition');
  if (await page.locator('#bulk-status option', { hasText: openStatus! }).count()) {
    await page.locator('#bulk-requests').getByLabel('Status').selectOption(openStatus!);
    await page.locator('#bulk-requests').getByRole('button', { name: 'Apply to selected requests' }).click();
    await expect(page.getByRole('alert').filter({ hasText: 'is already' })).toContainText(`is already ${openStatus}.`);
    await page.getByRole('row').filter({ hasText: requestSummary }).getByRole('checkbox').check();
  }
  await page.locator('#bulk-requests').getByLabel('Action').selectOption('assign');
  await page.locator('#bulk-requests').getByLabel('Assignee').selectOption('');
  await page.locator('#bulk-requests').getByRole('button', { name: 'Apply to selected requests' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'requests changed' })).toHaveText(/^1 of 1 requests changed\.$/);
  await expect(page.getByRole('row').filter({ hasText: requestSummary })).toHaveCount(0);
  const agentSettings = page.locator('#agents');
  await expect(agentSettings.getByRole('heading', { name: 'Agents' })).toBeVisible();
  await agentSettings.getByRole('button', { name: /Add agent Demo User/ }).click();
  await expect(page.locator('#agents').getByRole('button', { name: /Remove agent Demo User/ })).toBeVisible();
  await page.locator('#agents').getByRole('button', { name: /Remove agent Demo User/ }).click();
  await expect(page.locator('#agents').getByRole('button', { name: /Add agent Demo User/ })).toBeVisible();
  const knowledgeSettings = page.locator('#knowledge-base');
  await expect(knowledgeSettings.getByRole('heading', { name: 'Knowledge base' })).toBeVisible();
  await knowledgeSettings.getByRole('button', { name: `Link knowledge base Support knowledge ${key}` }).click();
  await expect(page.locator('#knowledge-base').getByRole('button', { name: `Unlink knowledge base Support knowledge ${key}` })).toBeVisible();
  // Deployments to a gated environment wait for an approved change request.
  await page.locator('#deployment-gating').getByLabel('Production').check();
  await page.locator('#deployment-gating').getByRole('button', { name: 'Save deployment gating' }).click();
  await expect(page.locator('#deployment-gating').getByLabel('Production')).toBeChecked();
  await page.locator('#deployment-gating').getByLabel('Production').uncheck();
  await page.locator('#deployment-gating').getByRole('button', { name: 'Save deployment gating' }).click();
  await expect(page.locator('#deployment-gating').getByLabel('Production')).not.toBeChecked();
  await page.goto(`/service/portals/${desk.id}?q=checkout`);
  await expect(page.getByRole('heading', { name: 'Suggested articles' })).toBeVisible();
  await page.getByRole('link', { name: new RegExp(`Resolve checkout errors ${key}`) }).click();
  await expect(page.getByRole('heading', { name: `Resolve checkout errors ${key}`, level: 1 })).toBeVisible();
  await expect(page.getByText('Restart the checkout worker and verify the payment queue.')).toBeVisible();
  await accessible(page);
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto(`/service/agent/${desk.id}`);
  const customerSettings = page.locator('#customers');
  await expect(customerSettings.getByRole('heading', { name: 'Customers' })).toBeVisible();
  const managedCustomerEmail = `managed-${Date.now()}@example.test`;
  await customerSettings.getByLabel('Display name').fill('Managed portal customer');
  await customerSettings.getByLabel('Email', { exact: true }).fill(managedCustomerEmail);
  await customerSettings.getByRole('button', { name: 'Invite customer' }).click();
  await expect(page.locator('#customers')).toContainText('Managed portal customer');
  await page.locator('#customers').getByRole('button', { name: 'Close portal access' }).click();
  await expect(page.locator('#customers').getByRole('button', { name: 'Open portal access' })).toBeVisible();
  await page.locator('#customers').getByRole('button', { name: 'Open portal access' }).click();
  // Jira's customer notifications can be turned off and on again per desk.
  const customerNotifications = page.getByRole('region', { name: 'Customer notifications' });
  await expect(customerNotifications.getByRole('listitem')).toHaveCount(6);
  await customerNotifications.getByRole('button', { name: 'Turn off Public comment added' }).click();
  await expect(page.getByRole('region', { name: 'Customer notifications' }).getByRole('listitem').filter({ hasText: 'Public comment added' })).toContainText('Turned off.');
  await page.getByRole('region', { name: 'Customer notifications' }).getByRole('button', { name: 'Turn on Public comment added' }).click();
  await expect(page.getByRole('region', { name: 'Customer notifications' }).getByRole('button', { name: 'Turn off Public comment added' })).toBeVisible();
  // The portal introduces itself with the text its administrators write.
  const portalSettings = page.getByRole('region', { name: 'Portal', exact: true });
  const portalName = await portalSettings.getByLabel('Portal name').inputValue();
  await portalSettings.getByLabel('Introduction text').fill('Laptops, access and office moves.');
  await portalSettings.getByLabel('Logo URL').fill('/static/img/avatar-default.svg');
  await portalSettings.getByLabel('Agents can add announcements to this portal').check();
  await portalSettings.getByRole('button', { name: 'Save portal' }).click();
  await expect(page.getByRole('region', { name: 'Portal', exact: true }).getByLabel('Introduction text')).toHaveValue('Laptops, access and office moves.');
  // With announcements allowed, the portal announces planned work.
  const portalAnnouncement = page.getByRole('region', { name: 'Portal announcement' });
  await portalAnnouncement.getByLabel('Announcement title').fill('Planned maintenance');
  await portalAnnouncement.getByLabel('Announcement message').fill('Laptop imaging is paused on Friday.');
  await portalAnnouncement.getByRole('button', { name: 'Save announcement' }).click();
  await expect(page.getByRole('region', { name: 'Portal announcement' }).getByLabel('Announcement title')).toHaveValue('Planned maintenance');
  await page.goto(`/service/portals/${desk.id}`);
  await expect(page.getByRole('heading', { name: portalName, level: 1 })).toBeVisible();
  await expect(page.locator('.service-hero')).toContainText('Laptops, access and office moves.');
  await expect(page.locator('.service-hero img.service-portal-logo')).toHaveAttribute('src', '/static/img/avatar-default.svg');
  await expect(page.getByRole('region', { name: 'Planned maintenance' })).toContainText('Laptop imaging is paused on Friday.');
  await accessible(page);
  await page.goto(`/service/agent/${desk.id}`);
  // Clearing the announcement removes it from the portal.
  await page.getByRole('region', { name: 'Portal announcement' }).getByLabel('Announcement title').fill('');
  await page.getByRole('region', { name: 'Portal announcement' }).getByLabel('Announcement message').fill('');
  await page.getByRole('region', { name: 'Portal announcement' }).getByRole('button', { name: 'Save announcement' }).click();
  await page.goto(`/service/portals/${desk.id}`);
  await expect(page.getByRole('region', { name: 'Planned maintenance' })).toHaveCount(0);
  await page.goto(`/service/agent/${desk.id}`);
  const organizationName = `Customer organization ${Date.now()}`;
  const organizationSettings = page.locator('#organizations');
  await organizationSettings.getByPlaceholder('Organization name').fill(organizationName);
  await organizationSettings.getByRole('button', { name: 'Create organization' }).click();
  const organizationCard = page.locator('#organizations article').filter({ hasText: organizationName });
  await expect(organizationCard).toBeVisible();
  await organizationCard.getByPlaceholder('Customer email or account ID').fill('demo@zzira.dev');
  await organizationCard.getByRole('button', { name: 'Add customer' }).click();
  await expect(page.locator('#organizations article').filter({ hasText: organizationName })).toContainText('Demo User');
  await page.locator('#organizations article').filter({ hasText: organizationName }).getByRole('button', { name: 'Link portal' }).click();
  await expect(page.locator('#organizations article').filter({ hasText: organizationName }).getByRole('button', { name: 'Unlink portal' })).toBeVisible();
  await page.goto('/service');
  await expect(page.getByRole('heading', { name: 'Your organizations' })).toBeVisible();
  await expect(page.locator('.service-organization-summary')).toContainText(organizationName);
  await page.goto(`/service/agent/${desk.id}`);
  const slaSettings = page.locator('#sla-settings');
  await expect(slaSettings.getByRole('heading', { name: 'Calendar and SLA goals' })).toBeVisible();
  await slaSettings.getByLabel('Starts').fill('08:00');
  await slaSettings.getByLabel('Ends').fill('18:00');
  await slaSettings.getByRole('button', { name: 'Save calendar' }).click();
  await expect(page.locator('#sla-settings').getByLabel('Starts')).toHaveValue('08:00');
  const holidaySettings = page.locator('#sla-settings .service-calendar-holidays');
  await holidaySettings.getByLabel('Holiday date').fill('2030-01-01');
  await holidaySettings.getByLabel('Holiday name').fill('Regional support shutdown');
  await holidaySettings.getByRole('button', { name: 'Add holiday' }).click();
  await expect(page.locator('#sla-settings .service-calendar-holidays')).toContainText('Regional support shutdown');
  await page.locator('#sla-settings .service-calendar-holidays').getByRole('button', { name: 'Remove holiday Regional support shutdown' }).click();
  await expect(page.locator('#sla-settings .service-calendar-holidays')).not.toContainText('Regional support shutdown');
  const calendarList = page.locator('#sla-settings .service-calendar-list');
  await expect(calendarList).toContainText('default');
  await calendarList.getByLabel('New calendar', { exact: true }).fill('Weekend cover');
  await calendarList.getByLabel('Opens').fill('10:00');
  await calendarList.getByLabel('Closes').fill('16:00');
  await calendarList.getByRole('button', { name: 'Add calendar' }).click();
  await expect(page.locator('#sla-settings .service-calendar-list')).toContainText('Weekend cover');
  await page.locator('#sla-settings .service-calendar-list').getByRole('button', { name: 'Remove Weekend cover' }).click();
  await expect(page.locator('#sla-settings .service-calendar-list')).not.toContainText('Weekend cover');

  const firstResponseGoal = page.locator('#sla-settings .service-sla-goals form').first();
  await firstResponseGoal.getByRole('spinbutton').fill('180');
  await firstResponseGoal.getByLabel('Pause while JQL matches').fill('status = "To Do"');
  await firstResponseGoal.getByRole('button', { name: 'Save SLA' }).click();
  await expect(page.locator('#sla-settings .service-sla-goals form').first().getByRole('spinbutton')).toHaveValue('180');
  await expect(page.locator('#sla-settings .service-sla-goals form').first().getByLabel('Pause while JQL matches')).toHaveValue('status = "To Do"');
  await page.locator('#sla-settings .service-sla-goals form').first().getByLabel('Pause while JQL matches').fill('');
  await page.locator('#sla-settings .service-sla-goals form').first().getByRole('button', { name: 'Save SLA' }).click();
  // Time to first response also stops when the request is assigned, until the condition is removed again.
  const firstResponseStop = () => page.locator('#sla-settings .service-sla-goals form').first().getByRole('group', { name: 'Stop counting time when' });
  await expect(firstResponseStop().getByLabel('Comment: For Customers')).toBeChecked();
  await firstResponseStop().getByLabel('Assignee: From Unassigned').check();
  await page.locator('#sla-settings .service-sla-goals form').first().getByRole('button', { name: 'Save SLA' }).click();
  await expect(firstResponseStop().getByLabel('Assignee: From Unassigned')).toBeChecked();
  await expect(page.locator('#sla-settings .service-sla-goals form').first().getByRole('group', { name: 'Start counting time when' }).getByLabel('Issue Created')).toBeChecked();
  await firstResponseStop().getByLabel('Assignee: From Unassigned').uncheck();
  await page.locator('#sla-settings .service-sla-goals form').first().getByRole('button', { name: 'Save SLA' }).click();
  await expect(firstResponseStop().getByLabel('Assignee: From Unassigned')).not.toBeChecked();
  // A manager adds their own SLA and removes it again.
  const customSLAName = `Time to approve ${String(Date.now()).slice(-6)}`;
  const createSLA = page.locator('#sla-settings .service-sla-create');
  await createSLA.getByLabel('SLA name').fill(customSLAName);
  await createSLA.getByRole('group', { name: 'Start counting time when' }).getByLabel('Issue Created').check();
  await createSLA.getByRole('group', { name: 'Stop counting time when' }).getByLabel('Resolution: Set').check();
  await createSLA.getByLabel('Goal in minutes').fill('120');
  await createSLA.getByRole('button', { name: 'Add SLA' }).click();
  const customSLAForm = page.locator('#sla-settings .service-sla-goals form').filter({ has: page.getByText(customSLAName, { exact: true }) });
  await expect(customSLAForm.getByRole('spinbutton')).toHaveValue('120');
  await expect(customSLAForm.getByRole('group', { name: 'Stop counting time when' }).getByLabel('Resolution: Set')).toBeChecked();
  await page.getByRole('button', { name: `Delete ${customSLAName}` }).click();
  await expect(page.getByRole('button', { name: `Delete ${customSLAName}` })).toHaveCount(0);
  const conditionalGoalName = `Incident response ${String(Date.now()).slice(-6)}`;
  const firstResponseConditions = page.locator('#sla-settings .service-conditional-goals section').filter({ has: page.getByRole('heading', { name: 'Time to first response conditions', level: 3 }) });
  const conditionalGoalCreate = firstResponseConditions.locator('.service-conditional-goal-create');
  await conditionalGoalCreate.getByLabel('Goal name').fill(conditionalGoalName);
  await conditionalGoalCreate.getByLabel('JQL condition').fill('labels = incident');
  await conditionalGoalCreate.getByLabel('Minutes').fill('60');
  await conditionalGoalCreate.getByRole('button', { name: 'Add conditional goal' }).click();
  const updatedConditionalGoalName = `${conditionalGoalName} priority`;
  const conditionalGoalCard = page.locator('#sla-settings .service-conditional-goal-list article').filter({ has: page.locator(`input[value="${conditionalGoalName}"]`) });
  await expect(conditionalGoalCard).toBeVisible();
  await conditionalGoalCard.getByLabel('Goal name').fill(updatedConditionalGoalName);
  await conditionalGoalCard.getByLabel('Minutes').fill('90');
  await conditionalGoalCard.getByRole('button', { name: 'Save conditional goal' }).click();
  await expect(page.locator('#sla-settings .service-conditional-goal-list article').filter({ has: page.locator(`input[value="${updatedConditionalGoalName}"]`) })).toBeVisible();
  // A second matching goal moved above the first takes new requests first.
  const topGoalName = `Top incident response ${String(Date.now()).slice(-6)}`;
  const topGoalCreate = page.locator('#sla-settings .service-conditional-goals section').filter({ has: page.getByRole('heading', { name: 'Time to first response conditions', level: 3 }) }).locator('.service-conditional-goal-create');
  await topGoalCreate.getByLabel('Goal name').fill(topGoalName);
  await topGoalCreate.getByLabel('JQL condition').fill('labels = incident');
  await topGoalCreate.getByLabel('Minutes').fill('30');
  await topGoalCreate.getByRole('button', { name: 'Add conditional goal' }).click();
  await page.locator('#sla-settings').getByRole('button', { name: `Move up ${topGoalName}` }).click();
  const firstResponseGoalNames = page.locator('#sla-settings .service-conditional-goals section').filter({ has: page.getByRole('heading', { name: 'Time to first response conditions', level: 3 }) }).locator('.service-conditional-goal-list article input[name="name"]');
  await expect(firstResponseGoalNames.nth(0)).toHaveValue(topGoalName);
  await expect(firstResponseGoalNames.nth(1)).toHaveValue(updatedConditionalGoalName);
  await expect(page.locator('#sla-settings').getByRole('button', { name: `Move up ${topGoalName}` })).toHaveCount(0);
  await expect(page.locator('#sla-settings').getByRole('button', { name: `Move down ${updatedConditionalGoalName}` })).toHaveCount(0);
  await page.goto(`/service/portals/${desk.id}/request/${incidentRequestType.id}`);
  const conditionalRequestSummary = `Priority incident ${Date.now()}`;
  await page.getByLabel('Summary').fill(conditionalRequestSummary);
  await page.getByLabel('Description').fill('This request should select the first matching conditional SLA goal.');
  await page.getByLabel(impactFieldName).fill('100');
  await page.getByRole('button', { name: 'Send request' }).click();
  await expect(page.getByRole('heading', { name: conditionalRequestSummary, level: 1 })).toBeVisible();
  await expect(page.locator('.service-sla-panel')).toContainText(topGoalName);
  await accessible(page);
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto(requestURL);
  await page.getByRole('button', { name: /Done/ }).click();
  await expect(page.locator('.service-current-status')).toHaveText('Done');
  await page.getByLabel('Satisfaction rating').fill('4');
  await page.getByLabel('Feedback comment').fill('Clear updates and a fast resolution.');
  await page.getByRole('button', { name: 'Save feedback' }).click();
  await expect(page.locator('#feedback')).toContainText('4 out of 5');
  await expect(page.locator('#feedback')).toContainText('Clear updates and a fast resolution.');
  await accessible(page);
  await page.goto(`/service/agent/${desk.id}/reports`);
  await expect(page.getByRole('heading', { name: 'Service reports', level: 1 })).toBeVisible();
  await expect(page.locator('.service-report-metrics article').filter({ hasText: 'Total requests' })).toContainText('6');
  await expect(page.getByText('4.0 / 5')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Request types', level: 2 })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Channels', level: 2 })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Daily request volume for the selected 30 day period' })).toBeVisible();
  await page.getByLabel('Status').selectOption('resolved');
  await page.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page).toHaveURL(/status=resolved/);
  const serviceCSV = await downloadCSV(page);
  expect(serviceCSV.lines[0]).toBe('Date,Requests created');
  expect(serviceCSV.lines.slice(1).reduce((sum, line) => sum + Number(line.split(',')[1]), 0)).toBe(1);
  await page.getByLabel('Compare with previous period').check();
  await page.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page).toHaveURL(/compare=previous/);
  await expect(page.locator('.service-report-metrics article').filter({ hasText: 'Total requests' }).locator('.report-change')).toContainText('previous 30 days');
  const comparedServiceCSV = await downloadCSV(page);
  expect(comparedServiceCSV.lines[0]).toBe('Period,Date,Requests created');
  expect(comparedServiceCSV.lines.filter((line) => line.startsWith('Current period,')).reduce((sum, line) => sum + Number(line.split(',')[2]), 0)).toBe(1);
  await expect(page.locator('.service-report-metrics article').filter({ hasText: 'Total requests' })).toContainText('1');
  await expect(page.locator('.service-report-metrics article').filter({ hasText: 'Open requests' })).toContainText('0');
  await page.getByRole('link', { name: '7 days' }).click();
  await expect(page.getByRole('link', { name: '7 days' })).toHaveAttribute('aria-current', 'page');
  await expect(page.getByLabel('Status')).toHaveValue('resolved');
  await accessible(page);
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto(`/service/agent/${desk.id}`);
  const dependencyMap = page.locator('#dependency-map');
  await expect(dependencyMap).toContainText(requestSummary);
  await expect(dependencyMap).toContainText(changeSummary);
  await expect(dependencyMap).toContainText('blocks');
  await accessible(page);
  await page.locator('#operations-settings').getByRole('button', { name: 'Remove shift Primary operations' }).click();
  await expect(page.locator('#operations-settings')).not.toContainText('Primary operations');
});
