import { expect, test } from '@playwright/test';
import axe from 'axe-core';
import * as fs from 'fs';
import * as path from 'path';

function apiAuthHeader(): string {
  const tokens = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', 'seed-tokens.json'), 'utf8'));
  const token = process.env.ZZIRA_API_TOKEN ?? tokens['demo@zzira.dev'];
  return 'Basic ' + Buffer.from(`demo@zzira.dev:${token}`).toString('base64');
}

async function accessible(page: import('@playwright/test').Page) {
  await page.addScriptTag({ content: axe.source });
  const violations = await page.evaluate(async () => (await (window as any).axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa'] } })).violations);
  expect(violations).toEqual([]);
}

test('admin creates a service project with Jira Service Management request types', async ({ page }) => {
  await page.goto('/login');
  await page.fill('#login-email', 'demo@zzira.dev');
  await page.fill('#login-password', 'demo1234');
  await page.click('button[type=submit]');
  const key = `S${String(Date.now()).slice(-7)}`;
  await page.goto('/projects/new');
  await page.getByLabel('Name').fill(`Service desk ${key}`);
  await page.getByLabel('Key').fill(key);
  await page.getByLabel('Template').selectOption('com.atlassian.servicedesk:simplified-it-service-management');
  await page.getByLabel('Description').fill('Customer requests and production incidents');
  await page.getByRole('button', { name: 'Create project' }).click();
  await expect(page).toHaveURL(`/projects/${key}`);
  await expect(page.getByRole('heading', { name: `Service desk ${key}`, level: 1 })).toBeVisible();

  const auth = { Authorization: apiAuthHeader() };
  const projectResponse = await page.request.get(`/rest/api/3/project/${key}`, { headers: auth });
  expect(projectResponse.status()).toBe(200);
  expect(await projectResponse.json()).toMatchObject({ key, projectTypeKey: 'service_desk' });
  const desksResponse = await page.request.get('/rest/servicedeskapi/servicedesk', { headers: auth });
  expect(desksResponse.status()).toBe(200);
  const desks = await desksResponse.json();
  const desk = desks.values.find((candidate: any) => candidate.projectKey === key);
  expect(desk).toBeTruthy();
  const requestTypesResponse = await page.request.get(`/rest/servicedeskapi/servicedesk/${desk.id}/requesttype`, { headers: auth });
  expect(requestTypesResponse.status()).toBe(200);
  const requestTypes = await requestTypesResponse.json();
  expect(requestTypes.values.map((requestType: any) => requestType.name)).toEqual(expect.arrayContaining(['Get IT help', 'Report an incident']));
  const fieldsResponse = await page.request.get(`/rest/servicedeskapi/servicedesk/${desk.id}/requesttype/${requestTypes.values[0].id}/field`, { headers: auth });
  expect(fieldsResponse.status()).toBe(200);
  expect((await fieldsResponse.json()).requestTypeFields).toEqual(expect.arrayContaining([expect.objectContaining({ fieldId: 'summary', required: true })]));

  await page.goto('/service');
  await expect(page.getByRole('heading', { name: 'How can we help?', level: 1 })).toBeVisible();
  await accessible(page);
  await page.getByRole('link', { name: `Service desk ${key}` }).click();
  await expect(page.getByRole('heading', { name: `Service desk ${key}`, level: 1 })).toBeVisible();
  await page.getByRole('link', { name: /Report an incident/ }).click();
  await expect(page.getByRole('heading', { name: 'Report an incident', level: 1 })).toBeVisible();
  const requestSummary = `Checkout incident ${Date.now()}`;
  await page.getByLabel('Summary').fill(requestSummary);
  await page.getByLabel('Description').fill('Customers receive an error when completing checkout.');
  await page.getByRole('button', { name: 'Send request' }).click();
  await expect(page).toHaveURL(new RegExp(`/service/requests/${key}-\\d+$`));
  await expect(page.getByRole('heading', { name: requestSummary, level: 1 })).toBeVisible();
  await expect(page.locator('.service-current-status')).toHaveText('To Do');
  await expect(page.getByRole('heading', { name: 'Service goals' })).toBeVisible();
  await expect(page.locator('.service-sla-panel')).toContainText('Time to first response');
  await expect(page.getByText('Customers receive an error when completing checkout.')).toBeVisible();
  const participantEmail = `participant-${Date.now()}@example.test`;
  const participantResponse = await page.request.post('/rest/servicedeskapi/customer', { headers: auth, data: { email: participantEmail, displayName: 'Incident stakeholder' } });
  expect(participantResponse.status()).toBe(201);
  await page.getByLabel('Add by account ID or email').fill(participantEmail);
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.locator('#participants')).toContainText('Incident stakeholder');
  await page.getByRole('button', { name: 'Remove Incident stakeholder' }).click();
  await expect(page.locator('#participants')).not.toContainText('Incident stakeholder');
  await page.getByLabel('Add to the conversation').fill('The impact is increasing across regions.');
  await page.getByRole('button', { name: 'Add comment' }).click();
  await expect(page.locator('.service-comments')).toContainText('The impact is increasing across regions.');
  await page.getByRole('button', { name: /In Progress/ }).click();
  await expect(page.locator('.service-current-status')).toHaveText('In Progress');
  await accessible(page);
  await page.locator('[data-theme-toggle]').click();
  await accessible(page);
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto('/service');
  await expect(page.locator('.service-request-list')).toContainText(requestSummary);
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto(`/service/agent/${desk.id}`);
  await expect(page.getByRole('heading', { name: 'Queues', level: 1 })).toBeVisible();
  await expect(page.getByRole('link', { name: 'SLA attention', exact: true })).toBeVisible();
  await expect(page.locator('.service-agent-table')).toContainText(requestSummary);
  await page.getByRole('link', { name: 'Unassigned requests', exact: true }).click();
  await expect(page.locator('.service-agent-table')).toContainText(requestSummary);
  const requestRow = page.getByRole('row').filter({ hasText: requestSummary });
  await requestRow.getByRole('button', { name: 'Assign to me' }).click();
  await page.getByRole('link', { name: 'Assigned to me', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: requestSummary }).getByRole('button', { name: 'Unassign' })).toBeVisible();
  const agentSettings = page.locator('#agents');
  await expect(agentSettings.getByRole('heading', { name: 'Agents' })).toBeVisible();
  await agentSettings.getByRole('button', { name: /Add agent Demo User/ }).click();
  await expect(page.locator('#agents').getByRole('button', { name: /Remove agent Demo User/ })).toBeVisible();
  await page.locator('#agents').getByRole('button', { name: /Remove agent Demo User/ }).click();
  await expect(page.locator('#agents').getByRole('button', { name: /Add agent Demo User/ })).toBeVisible();
  const slaSettings = page.locator('#sla-settings');
  await expect(slaSettings.getByRole('heading', { name: 'Calendar and SLA goals' })).toBeVisible();
  await slaSettings.getByLabel('Starts').fill('08:00');
  await slaSettings.getByLabel('Ends').fill('18:00');
  await slaSettings.getByRole('button', { name: 'Save calendar' }).click();
  await expect(page.locator('#sla-settings').getByLabel('Starts')).toHaveValue('08:00');
  const firstResponseGoal = page.locator('#sla-settings .service-sla-goals form').first();
  await firstResponseGoal.getByRole('spinbutton').fill('180');
  await firstResponseGoal.getByRole('button', { name: 'Save goal' }).click();
  await expect(page.locator('#sla-settings .service-sla-goals form').first().getByRole('spinbutton')).toHaveValue('180');
  await accessible(page);
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
