import { expect, test, Page } from '@playwright/test';
import axe from 'axe-core';

async function checkWikiAccessibility(page: Page) {
  await page.addScriptTag({ content: axe.source });
  const violations = await page.evaluate(async () => (await (window as any).axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa'] } })).violations);
  expect(violations).toEqual([]);
}


test('wiki space, rich page, access, stale edits, child pages, history, trash and restore', async ({ page, context, browser }) => {
  await page.goto('/login');
  await page.fill('#login-email', 'demo@zzira.dev');
  await page.fill('#login-password', 'demo1234');
  await page.click('button[type=submit]');
  await page.getByRole('link', { name: 'Wiki', exact: true }).click();
  await page.locator('.wiki-create-space > summary').click();
  const key = `W${Date.now().toString(36).toUpperCase()}`;
  await page.getByLabel('Space name').fill('Engineering handbook');
  await page.getByLabel('Space key').fill(key);
  await page.getByLabel('Description', { exact: true }).fill('How we build and release');
  await page.getByRole('button', { name: 'Create space', exact: true }).click();
  await expect(page).toHaveURL(/\/wiki\/spaces\/\d+$/);
  const spaceURL = page.url();
  await page.getByRole('link', { name: 'Create page', exact: true }).click();
  await checkWikiAccessibility(page);
  await page.getByLabel('Page title').fill('Release checklist');
  await page.getByRole('textbox', { name: 'Page content' }).fill('Review changes and publish release notes.');
  await page.getByRole('button', { name: 'Save page', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Release checklist', level: 1 })).toBeVisible();
  await expect(page.getByRole('article', { name: 'Page content' })).toContainText('Review changes');
  const pageURL = page.url().split('#')[0];
  const memberContext = await browser.newContext({ baseURL: new URL(pageURL).origin });
  const member = await memberContext.newPage();
  await member.goto('/login');
  await member.fill('#login-email', 'ana@zzira.dev');
  await member.fill('#login-password', 'ana12345');
  await member.click('button[type=submit]');
  await member.goto(pageURL);
  await expect(member.getByRole('heading', { name: 'Release checklist', level: 1 })).toBeVisible();
  await expect(member.getByRole('link', { name: 'Edit page', exact: true })).toBeVisible();
  await page.getByRole('region', { name: 'Labels' }).locator('summary').click();
  await page.getByLabel('Label names').fill('release-ready, handbook');
  await page.getByRole('button', { name: 'Add labels', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Remove label release-ready', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Remove label handbook', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Remove label handbook', exact: true })).toHaveCount(0);
  await page.getByText('Page access', { exact: true }).click();
  await page.getByLabel('Allow Demo User to view').check();
  await page.getByLabel('Allow Demo User to edit').check();
  await page.getByRole('button', { name: 'Save page access', exact: true }).click();
  await expect(page.getByLabel('Allow Demo User to view')).toBeChecked();
  await member.reload();
  await expect(member.getByText(/does not exist or you do not have permission/)).toBeVisible();
  await page.getByText('Page access', { exact: true }).click();
  await page.getByLabel('Allow Ana Soursop to view').check();
  await page.getByRole('button', { name: 'Save page access', exact: true }).click();
  await member.reload();
  await expect(member.getByRole('heading', { name: 'Release checklist', level: 1 })).toBeVisible();
  await expect(member.getByRole('link', { name: 'Edit page', exact: true })).toHaveCount(0);
  await member.getByText('Page access', { exact: true }).click();
  await expect(member.locator('.wiki-access')).toContainText('View access');
  await expect(member.getByRole('button', { name: 'Save page access', exact: true })).toHaveCount(0);
  await page.getByText('Page access', { exact: true }).click();
  await page.getByLabel('Allow Ana Soursop to edit').check();
  await page.getByRole('button', { name: 'Save page access', exact: true }).click();
  await member.reload();
  await expect(member.getByRole('link', { name: 'Edit page', exact: true })).toBeVisible();
  await page.getByText('Attach a file', { exact: true }).click();
  await page.getByLabel('File', { exact: true }).setInputFiles({ name: 'release-plan.txt', mimeType: 'text/plain', buffer: Buffer.from('Release plan v1') });
  await page.getByLabel('Comment', { exact: true }).fill('Initial release plan');
  await page.getByRole('button', { name: 'Upload file', exact: true }).click();
  await expect(page.getByRole('link', { name: 'release-plan.txt', exact: true })).toBeVisible();
  await page.getByText('Replace', { exact: true }).click();
  await page.getByLabel('Replacement file for release-plan.txt').setInputFiles({ name: 'release-plan.txt', mimeType: 'text/plain', buffer: Buffer.from('Release plan v2') });
  await page.getByLabel('Version comment').fill('Approved plan');
  await page.getByRole('button', { name: 'Replace file', exact: true }).click();
  await expect(page.locator('#wiki-attachments')).toContainText('Version 2');
  await page.getByText('Metadata', { exact: true }).click();
  await page.getByLabel('Add attachment labels').fill('release-file');
  await page.getByRole('button', { name: 'Add attachment labels', exact: true }).click();
  await expect(page.locator('#wiki-attachments')).toContainText('release-file');
  await page.getByText('Metadata', { exact: true }).click();
  await page.getByLabel('New property key').fill('release-state');
  await page.getByLabel('JSON value').fill('{"approved":false}');
  await page.getByRole('button', { name: 'Add property', exact: true }).click();
  await expect(page.locator('#wiki-attachments')).toContainText('release-state');
  await page.getByText('Edit property release-state', { exact: true }).click();
  const propertyEditor = page.locator('.wiki-attachment-properties details').filter({ hasText: 'Edit property release-state' });
  await propertyEditor.getByLabel('JSON value').fill('{"approved":true}');
  await propertyEditor.getByLabel('What changed?').fill('Approved for release');
  await propertyEditor.getByRole('button', { name: 'Save property', exact: true }).click();
  await expect(page.locator('#wiki-attachments')).toContainText('v2');
  await page.getByRole('button', { name: 'Remove attachment label release-file', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Remove attachment label release-file', exact: true })).toHaveCount(0);
  await checkWikiAccessibility(page);
  await page.locator('[data-theme-toggle]').click();
  await checkWikiAccessibility(page);
  await page.locator('[data-theme-toggle]').click();
  const stale = await context.newPage();
  await stale.goto(pageURL + '/edit');
  await page.getByRole('link', { name: 'Edit page', exact: true }).click();
  await page.getByRole('textbox', { name: 'Page content' }).fill('Run checks before publishing.');
  await page.getByLabel('What changed?').fill('Added release checks');
  await page.getByRole('button', { name: 'Save page', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Remove label release-ready', exact: true })).toBeVisible();
  await stale.getByRole('textbox', { name: 'Page content' }).fill('My unsaved changes');
  await stale.getByRole('button', { name: 'Save page', exact: true }).click();
  await expect(stale.getByRole('alert')).toContainText('page changed');
  await expect(stale.getByRole('textbox', { name: 'Page content' })).toHaveText('My unsaved changes');
  await stale.close();
  await page.getByText('Page history', { exact: true }).click();
  await expect(page.locator('.wiki-history')).toContainText('Added release checks');
  await page.getByLabel('Add a comment').fill('Release owner confirms readiness.');
  await page.getByRole('button', { name: 'Comment', exact: true }).click();
  const discussion = page.locator('#wiki-discussion');
  const topComment = discussion.locator('.wiki-comment-list > .wiki-comment').first();
  await expect(topComment).toContainText('Release owner confirms readiness.');
  await topComment.getByRole('button', { name: 'Like', exact: true }).click();
  await expect(topComment.getByRole('button', { name: 'Unlike · 1', exact: true })).toBeVisible();
  await topComment.locator(':scope > .wiki-comment-actions > details').filter({ hasText: /^Reply/ }).locator('summary').click();
  await topComment.getByLabel('Reply to Demo User').fill('Approval recorded.');
  await topComment.getByRole('button', { name: 'Reply', exact: true }).click();
  await expect(discussion).toContainText('Approval recorded.');
  const refreshedTopComment = discussion.locator('.wiki-comment-list > .wiki-comment').first();
  await refreshedTopComment.locator(':scope > .wiki-comment-actions > details').filter({ hasText: /^Edit/ }).locator('summary').click();
  const topActions = refreshedTopComment.locator(':scope > .wiki-comment-actions');
  await topActions.getByLabel('Edit comment').fill('Release owner confirms final readiness.');
  await topActions.getByLabel('What changed?').fill('Confirmed final state');
  await topActions.getByRole('button', { name: 'Save comment', exact: true }).click();
  await expect(discussion).toContainText('Release owner confirms final readiness.');
  await refreshedTopComment.getByText('Version history', { exact: true }).click();
  await expect(refreshedTopComment.locator('.wiki-comment-history')).toContainText('Confirmed final state');
  await refreshedTopComment.getByRole('button', { name: 'Unlike · 1', exact: true }).click();
  await expect(topActions.getByRole('button', { name: 'Like', exact: true })).toBeVisible();
  const reply = discussion.locator('.wiki-comment-replies .wiki-comment').first();
  await reply.locator(':scope > .wiki-comment-actions > details').filter({ hasText: /^Delete/ }).locator('summary').click();
  await reply.getByRole('button', { name: 'Confirm delete', exact: true }).click();
  await expect(discussion).not.toContainText('Approval recorded.');
  await checkWikiAccessibility(page);
  await page.getByRole('link', { name: 'Create child page', exact: true }).click();
  await page.getByLabel('Page title').fill('Rollback steps');
  await page.getByRole('textbox', { name: 'Page content' }).fill('Restore the previous release.');
  await page.getByRole('button', { name: 'Save page', exact: true }).click();
  await page.getByText('Move to trash', { exact: true }).click();
  await page.getByRole('button', { name: 'Confirm move to trash' }).click();
  await page.getByRole('link', { name: 'Trash', exact: true }).click();
  await page.getByRole('link', { name: 'Rollback steps', exact: true }).click();
  await page.getByText('Restore page', { exact: true }).click();
  await page.getByRole('button', { name: 'Confirm restore' }).click();
  await expect(page.getByRole('link', { name: 'Rollback steps', exact: true })).toBeVisible();
  await page.goto(spaceURL);
  await page.getByLabel('Find a page').fill('Release');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Release checklist', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Rollback steps', exact: true })).toHaveCount(0);
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await memberContext.close();
});
